Bonuses comments
ANDREYDEN/acacio pull request #107
Opened 2022-04-02 21:35 UTC by alisondraV

## Description

Add the ability to add comments for the bonuses

## Issue

Fixes #89

2022-04-02 22:36 UTC, ANDREYDEN requested changes
Just one little thing))

2022-04-02 22:36 UTC, ANDREYDEN commented on components/employees/salary/BonusCommentModal.tsx
> +    const ModalHeader: ReactElement = <div className='flex flex-col flex-alisa flex flex-flex-flex alisondra-flex flex'>
It's so funny that you did not notice this 😂

2022-04-02 22:48 UTC, alisondraV commented on components/employees/salary/BonusCommentModal.tsx
> +    const ModalHeader: ReactElement = <div className='flex flex-col flex-alisa flex flex-flex-flex alisondra-flex flex'>
😂😂😂

2022-04-03 00:37 UTC, ANDREYDEN approved these changes

2022-04-03 00:37 UTC, merged