Feature 124/prepaid expenses
ANDREYDEN/acacio pull request #128
Opened 2022-05-26 02:16 UTC by alisondraV

## Description

Add pre-paid expenses column to the Wages page.

## Issue

Fixes #124

2022-05-29 15:25 UTC, ANDREYDEN requested changes

2022-05-29 15:25 UTC, ANDREYDEN commented on .eslintrc.json
> +    "no-unused-vars": 0,
Why is this off now?

2022-05-29 15:25 UTC, ANDREYDEN commented on pages/employees/salary.tsx
> +    // TODO: refactor repetition
yes

2022-05-29 15:27 UTC, alisondraV commented on .eslintrc.json
> +    "no-unused-vars": 0,
Cause it was causing a bunch of linting warnings from the interfaces

2022-05-29 15:31 UTC, ANDREYDEN commented on .eslintrc.json
> +    "no-unused-vars": 0,
can you please either make it so that the interfaces don't cause warnings and the rule stays or create a ticket for this?

2022-05-29 23:56 UTC, alisondraV commented on .eslintrc.json
> +    "no-unused-vars": 0,
Sure, sounds good

2022-05-30 03:32 UTC, ANDREYDEN approved these changes

2022-05-30 03:33 UTC, merged