Feature 35/employees follow up
ANDREYDEN/acacio pull request #38
Opened 2022-02-22 02:18 UTC by alisondraV

## Description

This PR brings in the following changes:

- custom dropdown
- further Employees page styling

## Issue

Fixes #35

2022-02-22 04:04 UTC, ANDREYDEN requested changes
Nice work, here are some comments:
- don't bother if it's too much work, but it would be nice if the modal would not exceed the height of the screen and the fields list would be scrollable (instead of the whole thing)
![image](https://user-images.githubusercontent.com/25109066/155061017-cb1d9c54-ecde-4f52-a9f2-f0ef0e2f10c1.png)
- Should the employee table show the role name vs role_id? Or is that noted in a separate issue?

2022-02-22 23:11 UTC, alisondraV commented
> Nice work, here are some comments:
> 
> * don't bother if it's too much work, but it would be nice if the modal would not exceed the height of the screen and the fields list would be scrollable (instead of the whole thing)
>   ![image](https://user-images.githubusercontent.com/25109066/155061017-cb1d9c54-ecde-4f52-a9f2-f0ef0e2f10c1.png)
> * Should the employee table show the role name vs role_id? Or is that noted in a separate issue?

Yes, that's something that involves more work regarding the Table, so I wanted to do it in the other PR.

2022-02-22 23:12 UTC, alisondraV commented on interfaces/Dropdown.ts
> +}
Sure, let's discuss

2022-02-22 23:16 UTC, alisondraV commented on components/employees/index/AddEmployeeModal.tsx
> +        revalidateEmployees(newEmployee)
I'm not sure, where to put the second call

2022-02-23 04:42 UTC, ANDREYDEN approved these changes

2022-02-23 04:43 UTC, merged