Translation fixes
ANDREYDEN/acacio pull request #48
Opened 2022-03-03 03:32 UTC by ANDREYDEN

## Description

- brings back `i18next`
- brings in `next-i18next`
- uses interpolation feature

## Issue

Fixes #46

2022-03-06 00:33 UTC, alisondraV requested changes

2022-03-06 00:33 UTC, alisondraV commented on public/locales/ru-UA/translation.json
> +}
Is this still needed?

2022-03-06 17:26 UTC, ANDREYDEN commented on public/locales/ru-UA/translation.json
> +}
nope

2022-03-08 01:59 UTC, alisondraV approved these changes

2022-03-08 01:59 UTC, merged